language: java
jdk:
  - oraclejdk8

sudo: false
env:
  - TERM=dumb

script:
  - ./gradlew build --stacktrace

after_success:
  - ./gradlew jacocoTestReport coveralls --stacktrace

cache:
   directories:
   - $HOME/.gradle/caches/
