language: java
script: ./gradlew build --stacktrace
jdk:
  - oraclejdk8
after_success:
  - ./gradlew jacocoTestReport coveralls --stacktrace
sudo: false
cache:
   directories:
   - $HOME/.gradle/caches/